contact/urls.py
import imp
from django.urls import path
from . import views

app_name = "contact"

urlpatterns = [
    path('add/',views.addContact,name = "add-contact"),
]

khanalsujit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

url_patterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('contact', include('contact.urls')),
]

urlpatterns = static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + url_patterns

portfolio/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

contact/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    firstname = models.CharField(max_length = 50)
    lastname = models.CharField(max_length = 50)
    email = models.CharField(max_length = 200)
    message = models.CharField(max_length= 200)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.firstname
    class Meta:
        ordering = ['-date']

portfolio/models.py
from django.db import models

# Create your models here.

contact/views.py
from django.shortcuts import render, HttpResponse,redirect,get_object_or_404,reverse

from .models import Contact
from django.contrib import messages

# Create your views here.
def addContact(request):
    if request.method == "POST":
        firstname = request.POST.get("firstname")
        lastname = request.POST.get("lastname")
        email = request.POST.get("email")
        message = request.POST.get("message")

        if firstname=="" or lastname=='' or email=='' or message=='':
            messages.warning(request, "All fields Required")
            return redirect('/#contact')

        else:
            newContact = Contact(firstname=firstname, lastname=lastname, email=email, message=message)
            newContact.save()
            messages.success(request, "Message Sent Successfully.")
            return redirect('/#contact')

portfolio/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <style>
    #pageMessages {
      position: fixed;
      top: 70px;
      width: 400px;
      right:0px;
      float: right;
    }
    .align-right {
      -webkit-box-pack: end;
      justify-content: flex-end;
      float: right;
    }
    .alert {
      position: relative;
    }

    .alert .close {
      position: absolute;
      top: 5px;
      right: 5px;
      font-size: 1em;
    }

    .alert .fa {
      margin-right:.3em;
    }
  </style>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Fistey | My Portfolio</title>
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/mcstudios/glightbox/dist/js/glightbox.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
</head>
<body>
<!-- ////////////////////////////////////////////////////////////////////////////////////////
                               START SECTION 1 - THE NAVBAR SECTION  
/////////////////////////////////////////////////////////////////////////////////////////////-->
<nav class="navbar navbar-expand-lg navbar-dark menu shadow fixed-top">
    <div class="container">
      <a class="navbar-brand" href="">
        <h2><b>F</b>istey</h2>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item"><a class="nav-link active" aria-current="page" href="/">Home</a></li>
          <li class="nav-item"><a class="nav-link" href="#contact">contact</a>
          </li>
        </ul>
        <button type="button" class="rounded-pill btn-rounded">
          developer.sujitkhanal@gmail.com
          <span>
            <i class="fas fa-envelope"></i>
          </span>
        </button>
      </div>
    </div>
  </nav>
  <main>
    {% if messages %}
    {% for message in messages %}
    <div id="pageMessages" class="pageMessages col-lg-4 col-sm-10 col-xs-10 col-md-6 align-right" style="z-index: 999;">
      <div class="alert animated flipInX alert-{{ message.tags }} alert-dismissible">
        <strong><i class="fa fa-thumbs-up"></i>{% if message.tags == 'warning' %} Error! {% else %} Success! {% endif %}&nbsp;</strong>
        {{ message }}
        <span class="close" data-dismiss="alert">
          <i class="fa fa-times-circle"></i>
        </span>
      </div>
    </div>
    {% endfor %}
    {% endif %}
  </main>
{% block content %}
{% endblock %}

<footer class="footer">
  <div class="container">
    <div class="row">
      <!-- CONTENT FOR THE MOBILE NUMBER  -->
      <div class="col-md-4 col-lg-4 contact-box pt-1 d-md-block d-lg-flex d-flex">
        <div class="contact-box__info">
          <button type="button" class="rounded-pill btn-rounded">10sujitkhanal/
            <span><i class="fab fa-github"></i></span>
          </button>
        </div>
      </div>  
      <!-- CONTENT FOR EMAIL  -->
      <div class="col-md-4 col-lg-4 contact-box pt-1 d-md-block d-lg-flex d-flex">

        <div class="contact-box__info">
          <button type="button" class="rounded-pill btn-rounded">khanalsujit.com.np
            <span><i class="fas fa-code"></i></span>
          </button>
        </div>
      </div>
      <!-- CONTENT FOR LOCATION  -->
      <div class="col-md-4 col-lg-4 contact-box pt-1 d-md-block d-lg-flex d-flex">
        <div class="contact-box__info">
          <button type="button" class="rounded-pill btn-rounded">Pokhara, Nepal
            <span><i class="fas fa-map"></i></span>
          </button>
        </div>
      </div>
    </div>
  </div>

  <!-- START THE SOCIAL MEDIA CONTENT  -->
  <div class="footer-sm" style="background-color: #212121;">
    <div class="container">
      <div class="row py-4 text-center text-white">
        <div class="col-lg-6 col-md-6 mb-4 mb-md-0">
          © Copyright 2022 sujit | Created by Sujit Khanal 
        </div>
        <div class="col-lg-6 col-md-6">
          <a href="https://www.facebook.com/tijus.lanahk/"><i class="fab fa-facebook"></i></a>
          <a href="https://github.com/10sujitkhanal/" target="_blank"><i class="fab fa-github"></i></a>
          <a href="https://t.me/tijuslanahk" target="_blank"><i class="fab fa-telegram"></i></a>
        </div>
      </div>
    </div>
  </div>
</footer>

<a href="#" class="shadow btn-primary rounded-circle back-to-top">
  <i class="fas fa-chevron-up"></i>
</a>



   <script>
    setTimeout(() => {  
  $('#pageMessages').fadeOut('fast');  
}, 5000);
    </script>
    <script src="{% static 'assets/vendors/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/index.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<section id="home" class="intro-section">
    <div class="container">
      <div class="row align-items-center text-white">
        <!-- START THE CONTENT FOR THE INTRO  -->
        <div class="col-md-6 intros text-start">
          <h1 class="display-2">
            <span class="display-2--intro">Hello!, I'm Sujit Khanal</span>
            <span class="display-2--description lh-base" style="font-size:12">
              I am currently studing software engineering at Gandaki Collage Of Engineering and Science (GCES).<br><br>
              EAT(); SLEEP(); CODE(); REPEAT();
            </span>
          </h1>
          <a href="#contact" style="text-decoration: none;">
            <button type="button" class="rounded-pill btn-rounded">Get in Touch
              <span><i class="fas fa-arrow-right"></i></span>
            </button>
          </a>
        </div>
        <!-- START THE CONTENT FOR THE VIDEO -->
        <div class="col-md-6 intros text-end">
          <div class="video-box">
            <img src="{% static 'images/coding.png' %}" alt="Coding Image" class="img-fluid">
            
          </div>
        </div>
      </div>
    </div>
</section>
  
<section class="services">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 services mt-4 text-start">
          <div class="services__pic">
            <img src="{% static 'images/web-development.png' %}" alt="web development" class="img-fluid">
          </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 services mt-4">
          <div class="services__content">
            <div class="icon d-block fas fa-code"></div>
            <h3 class="display-3--title mt-1">web development</h3>
            <p class="lh-lg">
             I love coding. I am a django (python) developer. I have built a project like e-commerce, management system and many more.
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
  
  
  <section id="contact" class="get-started">
    <div class="container">
      <div class="row text-center">
        <h1 class="display-3 fw-bold text-capitalize">Get in Touch</h1>
        <div class="heading-line"></div>
        <p class="lh-lg">
          If you have any query you can ask question by filling this form.
        </p>
      </div>
      <div class="row text-white">
        <div class="col-12 col-lg-6 gradient shadow p-3">
          <div class="cta-info w-100">
            <h4 class="display-4 fw-bold">My Contact</h4><br>
            <ul class="cta-info__list">
              <li>Mail<i class="fas fa-envelope"></i>: developer.sujitkhanal@gmail.com</li>
              <li>Github<i class="fab fa-github"></i>: https://github.com/10sujitkhanal/</li>
              <li>Viber<i class="fab fa-viber"></i>: +977 9842765535</li>
              <li>Telegram<i class="fab fa-telegram"></i>: https://t.me/tijuslanahk</li>
              <li>Discord<i class="fab fa-discord"></i>: tijus.lanahk#6979</li>
              <li>Facebook<i class="fab fa-facebook"></i>: https://www.facebook.com/tijus.lanahk</i></li>
            </ul>
          </div>
        </div>
        <div class="col-12 col-lg-6 bg-white shadow p-3">
          <div class="form w-100 pb-2">
            <h4 class="display-3--title mb-5">Fill the form</h4>
            <form method = "post" action = "{% url 'contact:add-contact' %}" class="row">
              {% csrf_token %}
              <div class="col-lg-6 col-md mb-3">
                <input type="text" placeholder="First Name" name="firstname" id="inputFirstName" class="shadow form-control form-control-lg">
              </div>
              <div class="col-lg-6 col-md mb-3">
                <input type="text" placeholder="Last Name" name="lastname" id="inputLastName" class="shadow form-control form-control-lg">
              </div>
              <div class="col-lg-12 mb-3">
                <input type="email" placeholder="Your email address" name="email" id="inputEmail" class="shadow form-control form-control-lg">
              </div>
              <div class="col-lg-12 mb-3">
                <textarea name="message" placeholder="Write your message" name="message" id="message" rows="8" class="shadow form-control form-control-lg"></textarea>
              </div>
              <div class="text-center d-grid mt-1">
                <button type="submit" class="btn btn-primary rounded-pill pt-3 pb-3">
                  submit
                  <i class="fas fa-paper-plane"></i>
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}